CREATE TABLE `geoPlotMetaDataDimension` (
  `ID` INT(11) UNSIGNED NOT NULL COMMENT 'Links 1:1 with DBPlotID',
  `countryISO` VARCHAR(25) DEFAULT NULL,
  `countryStd` VARCHAR(150) DEFAULT NULL,
  `isInCountry` INT(1) DEFAULT NULL,
  `countryDistError` DOUBLE DEFAULT NULL,
  `stateProvinceStd` VARCHAR(150) DEFAULT NULL,
  `isInStateProvince` INT(1) DEFAULT NULL,
  `stateProvinceDistError` DOUBLE DEFAULT NULL,
  `countyParishStd` VARCHAR(150) DEFAULT NULL,
  `isInCountyParish` INT(1) DEFAULT NULL,
  `countyParishDistError` DOUBLE DEFAULT NULL,
  `isValidLatLong` INT(1) DEFAULT NULL,
  `isCultivated` INT(1) DEFAULT 0,
  `isCultivatedReason` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `geoP_countryISO_NDX`(`countryISO`),
  KEY `geoP_countryStd_NDX`(`countryStd`),
  KEY `geoP_isInCountry_NDX`(`isInCountry`),
  KEY `geoP_countryDistError_NDX`(`countryDistError`),
  KEY `geoP_stateProvinceStd_NDX`(`stateProvinceStd`),
  KEY `geoP_isInStateProvince_NDX`(`isInStateProvince`),
  KEY `geoP_stateProvinceDistError_NDX`(`stateProvinceDistError`),
  KEY `geoP_countyParishStd_NDX`(`countyParishStd`),
  KEY `geoP_isInCountyParish_NDX`(`isInCountyParish`),
  KEY `geoP_countyParishDistError_NDX`(`countyParishDistError`), 
  KEY `geoP_isValidLatLong_NDX`(`isValidLatLong`),
  KEY `geoP_isCultivated`(`isCultivated`),
  KEY `geoP_isCultivatedReason`(`isCultivatedReason`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `geoIndividualObservation` (
  `ID` INT(11) UNSIGNED NOT NULL COMMENT 'Links 1:1 with ObservationID',
  `countryISO` VARCHAR(25) DEFAULT NULL,
  `countryStd` VARCHAR(150) DEFAULT NULL,
  `isInCountry` INT(1) DEFAULT NULL,
  `countryDistError` DOUBLE DEFAULT NULL,
  `stateProvinceStd` VARCHAR(150) DEFAULT NULL,
  `isInStateProvince` INT(1) DEFAULT NULL,
  `stateProvinceDistError` DOUBLE DEFAULT NULL,
  `countyParishStd` VARCHAR(150) DEFAULT NULL,
  `isInCountyParish` INT(1) DEFAULT NULL,
  `countyParishDistError` DOUBLE DEFAULT NULL,
  `isValidLatLong` INT(1) DEFAULT NULL,
  `isCultivated` INT(1) DEFAULT 0,
  `isCultivatedReason` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `geoI_countryISO_NDX`(`countryISO`),
  KEY `geoI_countryStd_NDX`(`countryStd`),
  KEY `geoI_isInCountry_NDX`(`isInCountry`),
  KEY `geoI_countryDistError_NDX`(`countryDistError`),
  KEY `geoI_stateProvinceStd_NDX`(`stateProvinceStd`),
  KEY `geoI_isInStateProvince_NDX`(`isInStateProvince`),
  KEY `geoI_stateProvinceDistError_NDX`(`stateProvinceDistError`),
  KEY `geoI_countyParishStd_NDX`(`countyParishStd`),
  KEY `geoI_isInCountyParish_NDX`(`isInCountyParish`),
  KEY `geoI_countyParishDistError_NDX`(`countyParishDistError`), 
  KEY `geoI_isValidLatLong_NDX`(`isValidLatLong`),
  KEY `geoI_isCultivated`(`isCultivated`),
  KEY `geoI_isCultivatedReason`(`isCultivatedReason`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
