--
-- Table structure for table `geoscrub`
--

CREATE TABLE `geoscrub` (
`geoscrubID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`sourceTable` VARCHAR(50) NOT NULL,
`sourceID` int(11) UNSIGNED DEFAULT NULL,
`countryVerbatim` VARCHAR(100) DEFAULT NULL,
`countryID` INTEGER(11) UNSIGNED DEFAULT NULL,
`countryStd` VARCHAR(150) DEFAULT NULL,
`isInCountry` INT(1) DEFAULT NULL,
`distErrCountry` DOUBLE DEFAULT NULL,
`stateProvinceVerbatim` VARCHAR(100) DEFAULT NULL,
`stateProvinceID` INTEGER(11) UNSIGNED DEFAULT NULL,
`stateProvinceStd` VARCHAR(150) DEFAULT NULL,
`isInStateProvince` INT(1) DEFAULT NULL,
`distErrStateProvince` DOUBLE DEFAULT NULL,
`countyParishVerbatim` VARCHAR(100) DEFAULT NULL,
`countyParishID` INTEGER(11) UNSIGNED DEFAULT NULL,
`isInCountyParish` INT(1) DEFAULT NULL,
`distErrCountyParish` DOUBLE DEFAULT NULL,
`elevationVerbatim` VARCHAR(50) DEFAULT NULL,
`elevMaxVerbatim` VARCHAR(50) DEFAULT NULL,
`elevMinVerbatim` VARCHAR(50) DEFAULT NULL,
`latitudeDecimalVerbatim` DECIMAL(10,5) DEFAULT NULL,
`longitudeDecimalVerbatim` DECIMAL(10,5) DEFAULT NULL,
`isBadLatLong` INT(1) DEFAULT 0,
`badLatLongReason` VARCHAR(250) DEFAULT NULL,
`latitudeDecimalCorrected` DECIMAL(10,5) DEFAULT NULL,
`longitudeDecimalCorrected` DECIMAL(10,5) DEFAULT NULL,
`latLongCorrectedRemarks` VARCHAR(250) DEFAULT NULL,
`localityVerbatim` VARCHAR(1000) DEFAULT NULL,
`isCultivated` INT(1) DEFAULT 0,
`isCultivatedReason` VARCHAR(255) DEFAULT NULL,
isNewWorld INTEGER(1) NOT NULL DEFAULT 0,
PRIMARY KEY (`geoscrubID`),
INDEX (`sourceTable`),
INDEX (`sourceID`),
UNIQUE INDEX (`sourceTable`,`sourceID`),
INDEX (`countryVerbatim`),
INDEX (`countryID`),
INDEX (`countryStd`),
INDEX (`isInCountry`),
INDEX (`stateProvinceVerbatim`),
INDEX (`stateProvinceID`),
INDEX (`stateProvinceStd`),
INDEX (`isInStateProvince`),
INDEX (`countyParishVerbatim`),
INDEX (`countyParishID`),
INDEX (`isInCountyParish`),
INDEX (`isBadLatLong`),
INDEX (`badLatLongReason`),
INDEX (`isCultivated`),
INDEX (`isCultivatedReason`),
INDEX (isNewWorld)
)  ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

